name       : kactivitymanagerd
version    : 5.9.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.9.5/kactivitymanagerd-5.9.5.tar.xz : 07b46fe7f5101f2cf5291c4b9a05c9d3a574d131bf1690a71b0b30ff789fc049
license    :
    - GPL-2.0
    - GPL-3.0
component  : desktop.kde.core
libsplit   : no
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kglobalaccel-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
