name       : kactivitymanagerd
version    : 5.19.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.2/kactivitymanagerd-5.19.2.tar.xz : 6a4ac8f229a7dc8c26d4798b2e66f19f9bb933701f1c680fc3a793003ec4b1a2
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - GPL-3.0
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kglobalaccel-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
