name       : kactivitymanagerd
version    : 5.27.7
release    : 88
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/kactivitymanagerd-5.27.7.tar.xz : 2df245330612d79090980269ad7c4e776150598e583761ac83f628cc1ffafbb4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kglobalaccel-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
