name       : kactivitymanagerd
version    : 5.21.1
release    : 61
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.1/kactivitymanagerd-5.21.1.tar.xz : 43b605ad194884a058f31eef315bbf2397edaa309c7e79968a1a9349bd9ffcf3
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kglobalaccel-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
