name       : kactivitymanagerd
version    : 5.16.1
release    : 34
source     :
    - https://download.kde.org/stable/plasma/5.16.1/kactivitymanagerd-5.16.1.tar.xz : 63562dac3bd11421a8acddbe7bc4bafb61cb1b9cab706825c91b4b6dd5851c0d
license    :
    - GPL-2.0
    - GPL-3.0
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kglobalaccel-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
