name       : kactivitymanagerd
version    : 5.22.2
release    : 67
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/kactivitymanagerd-5.22.2.1.tar.xz : 9989958cb4974b278a655e231e75c5c45b52ffefc22638adabf9768d7c4fa0e9
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kglobalaccel-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
