name       : kactivitymanagerd
version    : 5.15.5
release    : 32
source     :
    - https://download.kde.org/stable/plasma/5.15.5/kactivitymanagerd-5.15.5.tar.xz : e38ec9074e0bc5c1a21bd5eee97b7d99e6528186918e832fecf1e3f95da239db
license    :
    - GPL-2.0
    - GPL-3.0
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kglobalaccel-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
