name       : kactivitymanagerd
version    : 5.10.1
release    : 2
source     :
    - https://download.kde.org/stable/plasma/5.10.1/kactivitymanagerd-5.10.1.tar.xz : cc522b85309071348bc8f9724d3de378ab1e9822416a9f046e1d3d0afdb9e10b
license    :
    - GPL-2.0
    - GPL-3.0
component  : desktop.kde.core
libsplit   : no
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kglobalaccel-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
