name       : kactivitymanagerd
version    : 5.21.4
release    : 64
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.4/kactivitymanagerd-5.21.4.tar.xz : 2684b61713223f7d8f1e064689fef13e54f2ade6b767a6229294e25bfce54a71
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kglobalaccel-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
