name       : kactivitymanagerd
version    : 5.13.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.1/kactivitymanagerd-5.13.1.tar.xz : 2749a045e7a411d96fb9748306d0473917d76f5dd95cdbbcf93b6db1f850603e
license    :
    - GPL-2.0
    - GPL-3.0
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kglobalaccel-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
