name       : kactivitymanagerd
version    : 5.22.4
release    : 68
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.4/kactivitymanagerd-5.22.4.tar.xz : db87d0eb15a81117e31937078b095939e23c375fd939fe0ac1d4edec31ada0ce
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kio-devel
    - kglobalaccel-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
