name       : kactivitymanagerd
version    : 5.18.5
release    : 49
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.5/kactivitymanagerd-5.18.5.tar.xz : 24f32eb4585d427ee62e08a9fa2f057353085c62644d6bec8fb4b2568e507ac7
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - GPL-3.0
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kglobalaccel-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
